replace_brand_dict={
'acurio latticeworks': 'acurio', 
'american kennel club':'akc',
'amerimax home products': 'amerimax',
'barclay products':'barclay',
'behr marquee': 'behr', 
'behr premium': 'behr', 
'behr premium deckover': 'behr', 
'behr premium plus': 'behr', 
'behr premium plus ultra': 'behr', 
'behr premium textured deckover': 'behr', 
'behr pro': 'behr', 
'bel air lighting': 'bel air',
'bootz industries':'bootz',
'campbell hausfeld':'campbell',
'columbia forest products': 'columbia',
'essick air products':'essick air',
'evergreen enterprises':'evergreen',
'feather river doors': 'feather river', 
'gardner bender':'gardner',
'ge parts':'ge',
'ge reveal':'ge',
'gibraltar building products':'gibraltar',
'gibraltar mailboxes':'gibraltar',
'glacier bay':'glacier',
'great outdoors by minka lavery': 'great outdoors', 
'hamilton beach': 'hamilton',
'hampton bay':'hampton',
'hampton bay quickship':'hampton',
'handy home products':'handy home',
'hickory hardware': 'hickory', 
'home accents holiday': 'home accents',
'home decorators collection': 'home decorators',
'homewerks worldwide':'homewerks',
'klein tools': 'klein',
'lakewood cabinets':'lakewood',
'leatherman tool group':'leatherman',
'legrand adorne':'legrand',
'legrand wiremold':'legrand',
'lg hausys hi macs':'lg',
'lg hausys viatera':'lg',
'liberty foundry':'liberty',
'liberty garden':'liberty',
'lithonia lighting':'lithonia',
'loloi rugs':'loloi',
'maasdam powr lift':'maasdam',
'maasdam powr pull':'maasdam',
'martha stewart living': 'martha stewart',
'merola tile': 'merola',
'miracle gro':'miracle',
'miracle sealants':'miracle',
'mohawk home': 'mohawk',
'mtd genuine factory parts':'mtd',
'mueller streamline': 'mueller',
'newport coastal': 'newport',
'nourison overstock':'nourison',
'nourison rug boutique':'nourison',
'owens corning': 'owens', 
'premier copper products':'premier',
'price pfister':'pfister',
'pride garden products':'pride garden',
'prime line products':'prime line',
'redi base':'redi',
'redi drain':'redi',
'redi flash':'redi',
'redi ledge':'redi',
'redi neo':'redi',
'redi niche':'redi',
'redi shade':'redi',
'redi trench':'redi',
'reese towpower':'reese',
'rheem performance': 'rheem',
'rheem ecosense': 'rheem',
'rheem performance plus': 'rheem',
'rheem protech': 'rheem',
'richelieu hardware':'richelieu',
'rubbermaid commercial products': 'rubbermaid', 
'rust oleum american accents': 'rust oleum',
'rust oleum automotive': 'rust oleum', 
'rust oleum concrete stain': 'rust oleum', 
'rust oleum epoxyshield': 'rust oleum', 
'rust oleum flexidip': 'rust oleum', 
'rust oleum marine': 'rust oleum', 
'rust oleum neverwet': 'rust oleum', 
'rust oleum parks': 'rust oleum', 
'rust oleum professional': 'rust oleum', 
'rust oleum restore': 'rust oleum', 
'rust oleum rocksolid': 'rust oleum', 
'rust oleum specialty': 'rust oleum', 
'rust oleum stops rust': 'rust oleum', 
'rust oleum transformations': 'rust oleum', 
'rust oleum universal': 'rust oleum', 
'rust oleum painter touch 2': 'rust oleum',
'rust oleum industrial choice':'rust oleum',
'rust oleum okon':'rust oleum',
'rust oleum painter touch':'rust oleum',
'rust oleum painter touch 2':'rust oleum',
'rust oleum porch and floor':'rust oleum',
'salsbury industries':'salsbury',
'simpson strong tie': 'simpson', 
'speedi boot': 'speedi', 
'speedi collar': 'speedi', 
'speedi grille': 'speedi', 
'speedi products': 'speedi', 
'speedi vent': 'speedi', 
'pass and seymour': 'seymour',
'pavestone rumblestone': 'rumblestone',
'philips advance':'philips',
'philips fastener':'philips',
'philips ii plus':'philips',
'philips manufacturing company':'philips',
'safety first':'safety 1st',
'sea gull lighting': 'sea gull',
'scott':'scotts',
'scotts earthgro':'scotts',
'south shore furniture': 'south shore', 
'tafco windows': 'tafco',
'trafficmaster allure': 'trafficmaster', 
'trafficmaster allure plus': 'trafficmaster', 
'trafficmaster allure ultra': 'trafficmaster', 
'trafficmaster ceramica': 'trafficmaster', 
'trafficmaster interlock': 'trafficmaster', 
'thomas lighting': 'thomas', 
'unique home designs':'unique home',
'veranda hp':'veranda',
'whitehaus collection':'whitehaus',
'woodgrain distritubtion':'woodgrain',
'woodgrain millwork': 'woodgrain', 
'woodford manufacturing company': 'woodford', 
'wyndham collection':'wyndham',
'yardgard select': 'yardgard',
'yosemite home decor': 'yosemite'
}
